#
# UR5 calibration data
#
Calibration:
  Camera: "D435i" # depricateda
  output_filename: "UR5_calibration.dat"
  # if values is "centers" the camera frame is estimated based on the centers of the tags
  # if values is "corners" the camera frame is estimated based on the corners of the tags
  CalibrationMode: "corners"
  TagSize: 0.0637 # m
  tags:
    tag_6:
      A: [ -0.156, -0.259, 0.005 ]
      B: [ -0.0921, -0.26, 0.005 ]
      C: [ -0.0929, -0.195, 0.005]  # x,y,z
      D: [ -0.156, -0.196, 0.005 ]
    tag_7:
      A: [ -0.0734, -0.259, 0.005 ]
      B: [ -0.00984, -0.259, 0.005 ]
      C: [ -0.0103, -0.195, 0.005 ]  # x,y,z
      D: [ -0.0736, -0.196, 0.005 ]
    tag_8:  # each corresponds to a tag ID
      A: [ -0.156, -0.342, 0.005 ]
      B: [ -0.0927, -0.342, 0.005 ]
      C: [ -0.0934, -0.278, 0.005 ]  # x,y,z
      D: [ -0.156, -0.279, 0.005 ]
    tag_9:
      A: [ -0.0742, -0.341, 0.005 ]
      B: [ -0.00944, -0.342, 0.005 ]
      C: [ -0.0104, -0.278, 0.005 ]  # x,y.z
      D: [ -0.0735, -0.278, 0.005 ]

























